spring:
  application:
    name: "TaskManager"

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 0545892b
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true